title: í‰ìƒ ê³µë¶€ ğŸŒ™
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
description: "í‰ìƒ ê³µë¶€ ë¸”ë¡œê·¸"
baseurl: ""
url: "https://github.com/Jpot777"

# Aux links for the upper right navigation
aux_links:
  "Github":
    - "//github.com/Jpot777"

permalink: pretty

exclude:
   - Gemfile
   - Gemfile.lock
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - README.md

favicon_ico: "/assets/images/bloglogo.png"

# Footer "Edit this page on Github" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on Github"
gh_edit_repository: "https://github.com/Jpot777"

# Enable or diable the site search
# Support true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 10
  # Set the search token separator
  # Default: /[|s|-/]+|
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"